# Over rides for default values in Helm Charts
destination_test: &test_ns ds-test
destination_staging: &staging_ns ds-staging
helm_repository: &helm_repo "https://nexus-ds-ci-cd.apps.s44.core.rht-labs.com/repository/helm-charts/"
##############
# Application Custom Values
#############
# toggle between versions of the app by setting the tag to grey / purple or latest
pet_battle: &front_end_values
  config_map: "'http://pet-battle-api-ds-test.apps.s44.core.rht-labs.com'"
pet_battle_api: &api_values
  appName: pet-battle-api
  image_repository: quay.io
  image_name: pet-battle-api
  image_namespace: eformat
  image_version: latest
##############
# Argo Ignore Differences
#############
ignore_differences: &ignore_differences
  ignoreDifferences:
    - group: apps.openshift.io
      kind: DeploymentConfig
      jsonPointers:
        - /spec/template/spec/containers/0/image
        - /spec/triggers/0/imageChangeParams/lastTriggeredImage
        - /spec/triggers/1/imageChangeParams/lastTriggeredImage
##############
# Argo App of Apps declaration
#############
applications:
  - name: test-pet-battle # Test App deployment 
    enabled: true
    source: *helm_repo
    source_path: ""
    chart_name: pet-battle # probs over written in jenkins
    sync_policy_automated: true
    destination: *test_ns
    source_ref: 1.0.0
    ignore_differences: *ignore_differences
  - name: test-pet-battle-api
    enabled: true
    source: https://eformat.github.io/helm-charts
    source_path: ""
    sync_policy_automated: true
    destination: *test_ns
    source_ref: master
    ignore_differences: *ignore_differences
    # Staging App deployment 
  - name: pet-battle
    enabled: true
    source: *helm_repo
    source_path: ""
    chart_name: pet-battle # probs over written in jenkins
    sync_policy_automated: true
    destination: *staging_ns
    source_ref: 1.0.0
    ignore_differences: *ignore_differences
  - name: pet-battle-api
    enabled: true
    source: https://eformat.github.io/helm-charts
    source_path: ""
    chart_name: pet-battle-api # probs over written in jenkins
    sync_policy_automated: true
    destination: *staging_ns
    source_ref: 1.0.0
    ignore_differences: *ignore_differences
