# Over rides for default values in Helm Charts
destination: &ci_cd_ns ds-ci-cd

##############
# 🛎 Jenkins Custom Values
#############
jenkins_values: &jenkins_values
  persistence: false
  source_secrets:
    - name: git-auth
      username: idm-sa
      password: thisisdefinitelymypassword
    - name: nexus-password
      username: admin
      password: admin123
    - name: argocd-token
      username: token
      password: aaa.bbb.ccc
  buildconfigs:
    - name: *name
      build_trigger_secret: 'shhhhh-this-is-my-super-duper-secret123-shhhhh'
      strategy_type: "Source"
      source_secret: 'git-auth'
      pull_secret: ''
      source_repo: https://github.com/rht-labs/s2i-config-jenkins.git
      source_repo_ref: v1.6
      source_context_dir: '/'
      builder_image_name: jenkins
      builder_image_tag: '2'
    - name: "jenkins-slave-mvn"
      strategy_type: "Docker"
      source_context_dir: "jenkins-slaves/jenkins-slave-mvn"
      source_repo: "https://github.com/redhat-cop/containers-quickstarts"
      source_repo_ref: "v1.22"
      builder_image_name: "quay.io/eformat/origin-jenkins-agent-maven"
      builder_image_tag: "latest"
    - name: "jenkins-slave-helm"
      strategy_type: "Docker"
      source_context_dir: "jenkins-slaves/jenkins-slave-helm"
      source_repo: "https://github.com/redhat-cop/containers-quickstarts"
      source_repo_ref: "master"
      builder_image_name: "quay.io/openshift/origin-jenkins-agent-base"
      builder_image_tag: "4.3"
    - name: "jenkins-slave-argocd"
      strategy_type: "Docker"
      source_context_dir: "jenkins-slaves/jenkins-slave-argocd"
      source_repo: "https://github.com/redhat-cop/containers-quickstarts"
      source_repo_ref: "master"
      builder_image_name: "quay.io/openshift/origin-jenkins-agent-base"
      builder_image_tag: "4.3"  
    - name: "jenkins-slave-npm"
      strategy_type: "Docker"
      source_context_dir: "jenkins-slaves/jenkins-slave-npm"
      source_repo: "https://github.com/redhat-cop/containers-quickstarts"
      source_repo_ref: "master"
      builder_image_name: "openshift/jenkins-slave-base-centos7"
      builder_image_tag: "v3.11"

##############
# 🛎 Pact Broker Custom Values
#############
pact_broker_values: &pact_broker_values
  secrets:
    name: pact-broker-secrets
    keys:
      pactBrokerDatabaseUsername: pact_broker_database_username
      pactBrokerDatabasePassword: pact_broker_database_password
      pactBrokerAdmin: pact_broker_admin
      pactBrokerAdminPassword: pact_broker_admin_password
      pactBrokerBasicAuthUsername: pact_broker_user
      pactBrokerBasicAuthPassword: pact_broker_user_password
    values:
      pactBrokerDatabaseUsername: pact_broker_user
      pactBrokerDatabasePassword: thisisdefinitelynotmypassword
      pactBrokerAdmin: admin
      pactBrokerAdminPassword: thisisdefinitelynotmypassword
      pactBrokerBasicAuthUsername: dev
      pactBrokerBasicAuthPassword: thisisdefinitelynotmypassword

##############
# 🛎 Sonatype Nexus Custom Values
#############
nexus_values: &nexus_values
  nexus:
    imageName: sonatype/nexus3
    imageTag: 3.22.1
    service:
      type: ClusterIP
    podAnnotations: {}
    securityContextEnabled: false

  route:
    enabled: true
    name: nexus
    portName: nexus-service
    path: null

  nexusProxy:
    enabled: false

  persistence:
    storageSize: 5Gi

  serviceAccount:
    name: nexus
    annotations: {}

  additionalConfigMaps:
    - name: maven-central
      labels:
        nexus-type: repository
      data:
        recipe: 'MavenProxy'
        remoteUrl: 'https://repo.maven.apache.org/maven2/'
        blobStoreName: 'default'
        strictContentTypeValidation: 'true'
        versionPolicy: 'RELEASE'
        layoutPolicy: 'STRICT'
    - name: labs-static
      labels:
        nexus-type: repository
      data:
        recipe: 'RawHosted'
        blobStoreName: 'default'
    - name: labs-npm
      labels:
        nexus-type: repository
      data:
        recipe: 'NpmProxy'
        blobStoreName: 'default'
        remoteUrl: 'https://registry.npmjs.org'
    - name: labs-charts
      labels:
        nexus-type: repository
      data:
        recipe: 'HelmHosted'
        blobStoreName: 'default'

  deployment:
    annotations: {}
    initContainers:
      - name: k8s-plugin-puller
        image: curlimages/curl:latest
        imagePullPolicy: Always
        command: ['sh','-c']
        args: ['curl -L -o /k8s-plugin/nexus-openshift-plugin.jar https://github.com/sonatype-nexus-community/nexus-kubernetes-openshift/releases/download/v0.2.8/nexus-openshift-plugin-0.2.8.jar']
        volumeMounts:
          - name: k8s-plugin
            mountPath: /k8s-plugin
    additionalVolumes:
      - name: k8s-plugin
        emptyDir: {}
    additionalVolumeMounts:
      - mountPath: /opt/sonatype/nexus/deploy/nexus-openshift-plugin.jar
        name: k8s-plugin
        subPath: nexus-openshift-plugin.jar

  service:
    enabled: true
    name: nexus-service
    labels: {}
    annotations: {}
    portName: nexus-service
    port: 8081
    targetPort: 8081
    ports: []

##############
# 🛎 Zalenium Custom Values
#############
## TODO: Update source URL as upstream when ArgoCD version is greater 1.5.0 or above
zalenium_values: &zalenium_values
  hub:
    serviceType: ClusterIP
    openshift:
      deploymentConfig:
        enabled: true
      route:
        enabled: true
    persistence:
      enabled: false
    serviceAccount:
      create: false
    desiredContainers: 0
    podAnnotations:
      app: zalenium

##############
# 🛎 Hoverfly Custom Values
# Values reference https://github.com/helm/charts/tree/master/incubator/hoverfly
#############
hoverfly_values: &hoverfly_values
  replicaCount: "1"
  openshift:
    route:
      admin:
        enabled: true
        hostname: ""
      proxy:
        enabled: true
        hostname: ""

##############
# 🛎 Wekan Custom Values
# Values reference https://github.com/wekan/wekan/tree/master/helm/wekan
#############
wekan_values: &wekan_values
  service:
    type: ClusterIP
  autoscaling:
    enabled: false
  mongodb-replicaset:
    replicas: 1
    securityContext:
      runAsUser: ""
      fsGroup: ""
  ingress:
    enabled: false
  route:
    enabled: true

##############
# 🛎 Mattermost Custom Values
# Values reference https://github.com/mattermost/mattermost-helm
#############
mattermost_values: &mattermost_values
  route:
    enabled: true
  mysql:
    mysqlRootPassword: "mysqlpass"
    mysqlUser: "mattermost"
    mysqlPassword: "matterpass"


##############
# 🐙 Argo Ignore Differences
#############
jenkins_ignore_differences: &jenkins_ignore_differences
  ignoreDifferences:
  - group: apps.openshift.io
    kind: DeploymentConfig
    jsonPointers:
    - /spec/template/spec/containers/0/image
    - /spec/triggers/0/imageChangeParams/lastTriggeredImage
  - group: build.openshift.io
    kind: BuildConfig
    jsonPointers:
    - /spec/triggers

nexus_ignore_differences: &nexus_ignore_differences
  ignoreDifferences:
  - group: route.openshift.io
    kind: Route
    jsonPointers:
    - /status/ingress

hoverflyignore_differences: &hoverfly_ignore_differences
  ignoreDifferences:
  - group: route.openshift.io
    kind: Route
    jsonPointers:
    - /status/ingress
    - /spec/host
  - group: apps/v1
    kind: Deployment
    jsonPointers:
    - /spec/replicas

crw_ignore_differences: &crw_ignore_differences
  ignoreDifferences:
  - group: org.eclipse.che
    kind: CheCluster
    jsonPointers:
    - /spec

dev-ex-dashboard_ignore_differences: &dev-ex-dashboard_ignore_differences
  ignoreDifferences:
  - group: apps.openshift.io
    kind: DeploymentConfig
    jsonPointers:
    - /spec/template/spec/containers/0/image
    - /spec/triggers/0/imageChangeParams/lastTriggeredImage
  - group: ''
    kind: ConfigMap
    jsonPointers:
    - /data

##############
# 🐙 Argo Sync Policy
#############
sync_policy_true: &sync_policy_true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      validate: true

sync_policy_no_selfheal: &sync_policy_no_selfheal
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
      validate: true

##############
# 🛎 Argo App of Apps declaration
#############

# enabled true on an app is to tell helm to create an argo app cr for this item
applications:
  - name: nexus
    enabled: true
    source: https://github.com/eformat/charts.git
    source_path: charts/sonatype-nexus
    source_ref: "feature/sonatype-nexus"
    sync_policy:
      *sync_policy_no_selfheal
    destination: *ci_cd_ns
    ignore_differences: *nexus_ignore_differences
  - name: jenkins
    enabled: true
    source: https://github.com/rht-labs/helm-charts.git
    source_path: charts/jenkins
    source_ref: "jenkins-0.0.12"
    sync_policy:
      *sync_policy_true
    destination: *ci_cd_ns
    values:
      *jenkins_values
    ignore_differences: *jenkins_ignore_differences
  - name: pact-broker
    enabled: false
    source: https://github.com/rht-labs/helm-charts.git
    source_path: charts/pact-broker
    source_ref: "pact-broker-0.0.2"
    sync_policy:
      *sync_policy_true
    destination: *ci_cd_ns
    values:
      *pact_broker_values
  - name: sonarqube
    enabled: false
    source: https://github.com/rht-labs/helm-charts.git
    source_path: charts/sonarqube
    source_ref: "sonarqube-0.0.4"
    sync_policy:
      *sync_policy_true
    destination: *ci_cd_ns
  - name: crw
    enabled: true
    destination: crw
    source: https://github.com/rht-labs/refactored-adventure
    source_path: crw/base
    source_ref: master
    sync_policy:
      *sync_policy_no_selfheal
    no_helm: true
    ignore_differences: *crw_ignore_differences
  - name: zalenium
    enabled: true
    source: https://github.com/zalando/zalenium.git
    source_path: charts/zalenium
    source_ref: "master"
    sync_policy:
      *sync_policy_true
    destination: *ci_cd_ns
    values:
      *zalenium_values
  - name: hoverfly
    enabled: false
    source: https://github.com/helm/charts.git
    source_path: incubator/hoverfly
    sync_policy:
      *sync_policy_true
    destination: *ci_cd_ns
    source_ref: "master"
    values:
      *hoverfly_values
    ignore_differences: *hoverfly_ignore_differences
  - name: wekan
    enabled: false
    source: https://github.com/wekan/wekan.git
    source_path: helm/wekan
    sync_policy:
      *sync_policy_true
    destination: *ci_cd_ns
    source_ref: "v4.01"
    values:
      *wekan_values
  - name: tekton
    enabled: false
    destination: crw
    source: https://github.com/rht-labs/refactored-adventure
    source_path: tekton/base
    source_ref: master
    sync_policy:
      *sync_policy_true
    no_helm: true
  - name: mattermost
    enabled: false
    source: https://github.com/mattermost/mattermost-helm.git
    source_path: charts/mattermost-team-edition
    destination: *ci_cd_ns
    source_ref: "mattermost-team-edition-3.10.0"
    values:
      *mattermost_values
  - name: etherpad
    enabled: false
    source: https://github.com/rht-labs/helm-charts.git
    source_path: charts/etherpad
    destination: *ci_cd_ns
    source_ref: "etherpad-0.0.1"
    sync_policy:
      *sync_policy_true
  - name: dev-ex-dashboard
    enabled: false
    source: https://github.com/rht-labs/helm-charts.git
    source_path: charts/dev-ex-dashboard
    destination: *ci_cd_ns
    source_ref: "dev-ex-dashboard-0.0.1"
    sync_policy:
      *sync_policy_no_selfheal
    ignore_differences: *dev-ex-dashboard_ignore_differences
