# Over rides for default values in Helm Charts
destination: &ci_cd_ns ds-ci-cd

##############
# 🛎 Jenkins Custom Values
#############
jenkins_values: &jenkins_values
  source_secrets:
    - name: git-auth
      username: idm-sa
      password: thisisdefinitelymypassword
    - name: nexus-password
      username: admin
      password: admin123
    - name: argocd-token
      username: token
      password: aaa.bbb.ccc
  buildconfigs:
    - name: jenkins
      build_trigger_secret: 'shhhhh-this-is-my-super-duper-secret123-shhhhh'
      strategy_type: "Source"
      source_secret: 'git-auth'
      pull_secret: ''
      source_repo: https://github.com/rht-labs/s2i-config-jenkins.git
      source_repo_ref: update-plugins-ocp4
      source_context_dir: '/'
      builder_image_name: jenkins
      builder_image_tag: '2'
    - name: "jenkins-slave-mvn"
      strategy_type: "Docker"
      source_context_dir: "jenkins-slaves/jenkins-slave-mvn"
      source_repo: "https://github.com/redhat-cop/containers-quickstarts"
      source_repo_ref: "v1.22"
      builder_image_name: "quay.io/eformat/origin-jenkins-agent-maven"
      builder_image_tag: "latest"
    - name: "jenkins-slave-helm"
      strategy_type: "Docker"
      source_context_dir: "jenkins-slaves/jenkins-slave-helm"
      source_repo: "https://github.com/redhat-cop/containers-quickstarts"
      source_repo_ref: "master"
      builder_image_name: "quay.io/openshift/origin-jenkins-agent-base"
      builder_image_tag: "4.3"
    - name: "jenkins-slave-argocd"
      strategy_type: "Docker"
      source_context_dir: "jenkins-slaves/jenkins-slave-argocd"
      source_repo: "https://github.com/redhat-cop/containers-quickstarts"
      source_repo_ref: "master"
      builder_image_name: "quay.io/openshift/origin-jenkins-agent-base"
      builder_image_tag: "4.3"  
    - name: "jenkins-slave-npm"
      strategy_type: "Docker"
      source_context_dir: "jenkins-slaves/jenkins-slave-npm"
      source_repo: "https://github.com/redhat-cop/containers-quickstarts"
      source_repo_ref: "master"
      builder_image_name: "openshift/jenkins-slave-base-centos7"
      builder_image_tag: "v3.11"
  imagestreams:
    # Jenkins Imagestream for custom build or external
    - name: jenkins
    # Jenkins agents image streams
    - name: jenkins-slave-mvn
    - name: jenkins-slave-argocd
    - name: jenkins-slave-helm
    - name: jenkins-slave-npm

##############
# 🐙 Argo Ignore Differences
#############
jenkins_ignore_differences: &jenkins_ignore_differences
  ignoreDifferences:
  - group: apps.openshift.io
    kind: DeploymentConfig
    jsonPointers:
    - /spec/template/spec/containers/0/image
    - /spec/triggers/0/imageChangeParams/lastTriggeredImage
  - group: build.openshift.io
    kind: BuildConfig
    jsonPointers:
    - /spec/triggers

nexus_ignore_differences: &nexus_ignore_differences
  ignoreDifferences:
  - group: route.openshift.io
    kind: Route
    jsonPointers:
    - /status/ingress

hoverflyignore_differences: &hoverfly_ignore_differences
  ignoreDifferences:
  - group: route.openshift.io
    kind: Route
    jsonPointers:
    - /status/ingress
    - /spec/host
  - group: apps/v1
    kind: Deployment
    jsonPointers:
    - /spec/replicas

crw_ignore_differences: &crw_ignore_differences
  ignoreDifferences:
  - group: org.eclipse.che
    kind: CheCluster
    jsonPointers:
    - /spec

dev-ex-dashboard_ignore_differences: &dev-ex-dashboard_ignore_differences
  ignoreDifferences:
  - group: apps.openshift.io
    kind: DeploymentConfig
    jsonPointers:
    - /spec/template/spec/containers/0/image
    - /spec/triggers/0/imageChangeParams/lastTriggeredImage
  - group: ''
    kind: ConfigMap
    jsonPointers:
    - /data

##############
# 🐙 Argo Sync Policy
#############
sync_policy_true: &sync_policy_true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      validate: true

sync_policy_no_selfheal: &sync_policy_no_selfheal
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
      validate: true

##############
# 🛎 Argo App of Apps declaration
#############

# enabled true on an app is to tell helm to create an argo app cr for this item
applications:
  - name: nexus
    enabled: true
    source: https://github.com/rht-labs/charts.git
    source_path: charts/sonatype-nexus
    source_ref: "sonatype-nexus-0.0.1"
    sync_policy:
      *sync_policy_no_selfheal
    destination: *ci_cd_ns
    ignore_differences: *nexus_ignore_differences
  - name: jenkins
    enabled: true
    source: https://github.com/rht-labs/helm-charts.git
    source_path: charts/jenkins
    source_ref: "jenkins-0.0.12"
    sync_policy:
      *sync_policy_true
    destination: *ci_cd_ns
    values:
      *jenkins_values
    ignore_differences: *jenkins_ignore_differences
  - name: pact-broker
    enabled: false
    source: https://github.com/rht-labs/helm-charts.git
    source_path: charts/pact-broker
    source_ref: "pact-broker-0.0.2"
    sync_policy:
      *sync_policy_true
    destination: *ci_cd_ns
    values:
      *pact_broker_values
  - name: sonarqube
    enabled: false
    source: https://github.com/rht-labs/helm-charts.git
    source_path: charts/sonarqube
    source_ref: "sonarqube-0.0.4"
    sync_policy:
      *sync_policy_true
    destination: *ci_cd_ns
  - name: crw
    enabled: true
    destination: crw
    source: https://github.com/rht-labs/refactored-adventure
    source_path: crw/base
    source_ref: master
    sync_policy:
      *sync_policy_no_selfheal
    no_helm: true
    ignore_differences: *crw_ignore_differences
  - name: zalenium
    enabled: false
    source: https://github.com/zalando/zalenium.git
    source_path: charts/zalenium
    source_ref: "master"
    sync_policy:
      *sync_policy_true
    destination: *ci_cd_ns
    values:
      *zalenium_values
  - name: hoverfly
    enabled: false
    source: https://github.com/helm/charts.git
    source_path: incubator/hoverfly
    sync_policy:
      *sync_policy_true
    destination: *ci_cd_ns
    source_ref: "master"
    values:
      *hoverfly_values
    ignore_differences: *hoverfly_ignore_differences
  - name: wekan
    enabled: false
    source: https://github.com/wekan/wekan.git
    source_path: helm/wekan
    sync_policy:
      *sync_policy_true
    destination: *ci_cd_ns
    source_ref: "v4.01"
    values:
      *wekan_values
  - name: tekton
    enabled: false
    destination: crw
    source: https://github.com/rht-labs/refactored-adventure
    source_path: tekton/base
    source_ref: master
    sync_policy:
      *sync_policy_true
    no_helm: true
  - name: mattermost
    enabled: false
    source: https://github.com/mattermost/mattermost-helm.git
    source_path: charts/mattermost-team-edition
    destination: *ci_cd_ns
    source_ref: "mattermost-team-edition-3.10.0"
    values:
      *mattermost_values
  - name: etherpad
    enabled: false
    source: https://github.com/rht-labs/helm-charts.git
    source_path: charts/etherpad
    destination: *ci_cd_ns
    source_ref: "etherpad-0.0.1"
    sync_policy:
      *sync_policy_true
  - name: dev-ex-dashboard
    enabled: false
    source: https://github.com/rht-labs/helm-charts.git
    source_path: charts/dev-ex-dashboard
    destination: *ci_cd_ns
    source_ref: "dev-ex-dashboard-0.0.1"
    sync_policy:
      *sync_policy_no_selfheal
    ignore_differences: *dev-ex-dashboard_ignore_differences
