# Over rides for default values in Helm Charts
destination: &ci_cd_ns my-ci-cd

##############
# 🛎 Jenkins Custom Values
#############
jenkins_values: &jenkins_values
  source_secrets: {}
  sealed_secrets:
    - name: git-auth
      password: AgB5TubkWImIq4uikIR523aYuy+0mTqtCKTs2UU3JZi6XSr0/ePeVmOSTCwgmK1bwtkrTsAvhAbolbf+FDcEcJyIWbHnwj3Ocp2/YBKpNrmnnc+BQHFgM+3GbBeG3ZPGJP7dPya0vmf/IWjWurHOzGl4ltI6Wya9X7f25OSG4JAWKQN8mefFEMqNs8uDVPHKdCm3eKWdR8rwVrMCdFB3wv8O+Rls1vHoLgJZsfyHm79XwUlReGuquXB+3/n9owTRhD9aTaWTEFiAzkk9p11epoPqCIDEJlMbfoD1aaWlKOtMRFQNHHh4tol52LrcV+F1/SMsKCiW1vKoyqOWR4GNIkJIwTN4Jzn8jDB5D3UhjHyUA0GrTTas1cg4OIas4EVZSak6R4tTDAMlqIL6hxbZqK1K5SwY6/R25zcRCjAXaRHu0/CnXU4DH76pP+BU2BR/hWp7+VoLHXt/SYkRFchlRreicEEhKXSAczNC+ASjl1L3Z3syqR75Nl8yqSkavHt3waOdypCpssGCZrqvOnYDWKlBcRg7sdZ5n+sw0/J0pb396t0HUtT3LJ0TMwCn3bOkae0+SGBv95fSn4QJPI4nELzzeKeF5B3GLofuXWHOgkRTyb14/bo1x4h9JBFLQwNvJtYBntq6tMj30nvZBBCTbetvGx6dOOW4DKAly/kADgLF2K6wzYWSmet8PGcllOx6Gd4fO8W2hPEQBQ//I7iVYJwp1j8T3GWXkZGRgPDHMTJD+K8vNEYddLYV
      username: AgCa5xZ+OfA9AQ6yHtWmSmY7gGprpQDtls2qkIM4668WpUEB1m1F438EmvYOs7/EC1XFgML9yMPH57C1GFtOo55MHdkdnzerDrAEM6aeFaRAJzJny9vSgwMU+5YEMpfM4IpUV/3GnAxC//gjsWtsuoDBIvyHVEr1fCfEqgUthBE0BBiI1kMrfmraosn1qjPEFHzLDJHY9GSOHIt6JTVDnLfXM422+mW6T0TwWErx0KZeVFOMrJsnY0OdaWDn7hvK9wsc0cr5PBHsFS9WRB/99bc5lDAR7Gtk8K/GDzTT7mRtPoM6vpVsjvhbXNNC2UYocoEkFMkHPLHKDmAPuuMRhgkfhhTs2MRj2A8iCkzvwWjrdlGJ7QjXEDR5hiB0tEudZqp9up300UfQeUGJXIpUx9g+qk931fV6Ru79fUo0pSq1VneN0jE1XPl/IjpmzKi6Gt17SKinu2k48k+Y7u7RaJM3+ByEeeYzqv3autnf89EG+RAS7ljgJKRIDX5AGeor9P16QM7zPobnvu0bVNbzvF93WPx/pOXFeh3UiP8mbwMI8Zv0RzUZl/AQuOaaZv9dNyGkTJZDCVUKN5YtVS/eBEMixTxIIMSp2iaOHeipn2wiymPiHmdHlhoxCeuJcqAw0/cEwhJs1O+z4z1GubidDAOgndf93ajjEjHzjUhusfmgGL+HfnsV2LNgZOMnAjoi9i9aZCyoNHjAYQ==
    - name: nexus-password
      password: AgCt5eaBg2CmXkwlPOsCyzsUu/6FxP7VH/YnKVv+eSHnR397KQCfz0X3JASRCKZvIRUIJPJMHb9rjaJ/g9EM4v1GSbIP5KW7gL1DMUSoeHtU69+9A7QYB9VF3PbGPS7vhPaxjBN7PLp4ulkgb9j4TLHb8+sQR7zLykr/mF5YeaYpwYwlsa3+s7SAkvIpdq9gMzZN8LORfhcrJCOp7WVKDRBxYSHv1OtQVWR4xPL6hyFjkELhiiGI3LStSNChr6uHFu6WEJT/CIxql45qaczieZU+uRJ3klVQUQ7V+XvhUIRIyB3I/AfDyBmXcYBXSIukkFWF5+WeI07iKeTkGoWHy5aGkY+Cn8Ts1y3fHBtaCLI1H+MNol0APWrt4QzLhoLRQEi9d6R0D5pe5F9PAj6zcTbQPrZ1S1318smM7Y5KKh+7QpX5okSYKt4wJUu6YE+QpadhvNVwGt5UYIZiDx3QtsUs2Vs7EvDKRjZxNomqSqcjIaF/Pgf/o6TvHxNYnZVTD/yDpJjKoKWkf2pFGZsbLMZLhnNSfeQnBgSGIrFQDMZF4ekt1DPGE/pPOzbbrJM2nCsXFo1ult6nID7zb45rNO0ao1ciQbrWA4VMHeBVmlWXGsSAqHZqDYf9PonFsK8KKVfV1wtlbzx5awwvacBC3feuaFd9zemL/Hk0xzfJ7pT8pSEOBYf+Yx6GYAFMoai4UnGz7NN0wVqt4A==
      username: AgBgnWfOMW4OjZiNjoT0ziWNVCVYc7QrSGxQtj7+xNa0YTYzgm5fFrIavatfCLkerLvbIrRfIhfw47G0Wb/aLhXtDFuGhO9p+ZU3cSTyhvhUdATbKWOFvvhfnua4g8mchdi5bT70Wo8xlvdyCPk7nz8iyADZMIN1BhaJZihzUgdxlMXJwFWL7dD1XmVbtVLYuCe4NZWWyIco8ytclD53VI0zwK/SdzwcRxVPV2Yp29hJ9s51lgtLOPQasG1HcrN9nfl0XO/ts+CsEuqdQgg0wKBNWF2oTnLqhBH4T+w2sczZ9mdOWt//JjTuCObb6/b3LGCbNHj8KVvIL1/dIO+nQj+dpJ6sLFdJNVG4XA2TwiLVEJ6pKvwn7NyMSGPEb/Lq0654EZtwbcv4Sb4PCM1j4PtN64WBRITSku4dt1ey/SVVVI4vM0Xfb1qqnryPxdNzJ4q1JnmP/gfJobOAwwHSs/Si7UKA3M67w52LztNNgncUVDB7Ol5P+kGVsxL0S5ODJutYtEHs8ltPeaagYEg68PNgTv8vsnXIIwpGr3cu9XYWZWt8zJapJmXPP1icuLePu4G1CQ9m1bzuEllMiMLRX4/l778gESKOzIBHyQeICPQW4IY8Oa3kl44n2SaB4l8I+C+ODoVn0+aM9EWr+8tuDyWX44C8+eNW6Qu+nUczUxVLMU226Vg2fyOEn48C2bh75dE84qpxdA==
    - name: argocd-token
      password: AgAbclndpOhe3w/0GncBCo0CGuewF6T1KKh+2xu6Q/6zNkiuipsA7qYytkbtO8gvwSo747TZPodQ4PqQ8Mu4EHIUDHmdFHzEqec+8Kh2PADeO+a/8rBxWcJWGbVVLjJanZSwmltwcrjkrq9q8ZI3gC5MW/iP3c5Ui2ogdlrN9VZBwYGAbrGQGhm4EvnZH28B59N4dLiMSlMvV9DXkRqqYlo8GmddmtY2EhXlgJWWw5LlDauflliq6Fp9ggqnp/e/2oJkGNmCXnYnpMZIsxAA9amUo67A4zhKS/u+LLMXYhedHA3leMItZROuo6/sVhNIX7cN9n129miPPkZjBqLgF85ppCKj3s/QaTxJXWSvLKuWfihYgkCbEPWGXlhpC0/0XG6ms4QiewzLVxRLs0ESUhwkdF6JpbDTeMB/mRXtot3Mtx4Aoe9qstPDtUWO8SWowfybLEn521RnI4rw0Hj/b4DpvdPylcpecm/LYtxkV7CJlF2veFyykPovcIaY1Z7xkpz6Cdnv8v1fzV9Pq79C2Xsaewbj47TPLPfKQV9vUUQ/IG2hJwn2bknSajZQ4muBdy3EgYmNBGV5upO5dhLFzOs4c6+nXqfBMsKsAwFX/tFiuVXlJ7iokVMOFaoa1Alvzd45J/aH0A6DHOW5pNLiIfTg78W4Mr+fNxUTkL8tEltKTcPBJ/KBhZD4x5phTJ04oogq4ZOFEQT8qRiAP4rkHaxFE3uH5hiIqc0kKlt5f4LvfDjM3jU6EBNiVNqggfqjtoCO25Dwuc+fTDLPnvyo6Iyz1nsPeBLztqsgeQMtxo3fAFzzKwLH1anfjj9LsYWhyJvoBT+KUAZxqXGM5nt8jUe7Mqzi4yppFm5vZkPxQ7J3RwMFvjfwKfsT6TJfoON3vBuP3OPEh48WgweigdFMv2vkM3TxLG4ejZCMjDh37Vohe3K4f5E2PzUrA1actMjpsLmFVKMhjKk3T0AlfUWflnt5xCwR9hKXCSSSw8TMyR7SSBne1g==
      username: AgBCZDAfQyG6GaQubejI+tqN/t838M3pe50y1I0HHRLux9V/SKCz+4/AGpj6pSu9o6r6Hf9kWlvLAYAEYc+B2DMVnlYvFBUXZB5TuACb+tNshIXxAjeUHaT4JBg2587n7+hVX9QjdUOVh7Bclck7VQRx0u00NsHQ8g1R9gURf/g1BOiplsFbtxjMcB0Ucn97p5xkqHp+zCLcvy2P65PJ8loCd0No3RgtKHK36YVX/AW5IgvMiqpIAx+ba7MecVu8ZA8gadZb68WroU7XzfLPamDBOwAzC0QSAeulbccl/4wzThE7pbgeHpr8EBh9QD4hRzBtV3PIlz8wu9OXclHVOQMfZ7Xy4XK3OVIyIDYyQw/Ya9AW1XlJ2DO+BMNe1QWHGIXOl7uOQdciwNK04GdtGhI4vjpWSoIclnrkzf/3vdXBMpy2BlF5OjzniqeYwPkk1qHR4oFSVIgurcX9cA/EeyXToNVwnqSMg77Vy7WprfgI4/53xUtgh764m2zMlftr/+WCz9Z19M0p/JSaAdAXnxgJOj4ILDq+Ic2HWBtDdJAUEcrQ7vJvRTPAflmnGQPvvdiSrdVUvdfwILuTWLg08Dx/AP6J516sEq83C3KTFgalDq9Oxu7hUfKppnUG1gvyaQiPridVggooLEWNYjRTkZ2CYmBQzKCgeGt10DP2b+onWDC+2DqrCbtqVfnoZtXWihZoc09THA==

##############
# 🛎 Pact Broker Custom Values
#############
pact_broker_values: &pact_broker_values
  secrets:
    name: pact-broker-secrets
    keys:
      pactBrokerDatabaseUsername: pact_broker_database_username
      pactBrokerDatabasePassword: pact_broker_database_password
      pactBrokerAdmin: pact_broker_admin
      pactBrokerAdminPassword: pact_broker_admin_password
      pactBrokerBasicAuthUsername: pact_broker_user
      pactBrokerBasicAuthPassword: pact_broker_user_password
    values:
      pactBrokerDatabaseUsername: pact_broker_user
      pactBrokerDatabasePassword: thisisdefinitelynotmypassword
      pactBrokerAdmin: admin
      pactBrokerAdminPassword: thisisdefinitelynotmypassword
      pactBrokerBasicAuthUsername: dev
      pactBrokerBasicAuthPassword: thisisdefinitelynotmypassword

##############
# 🛎 Zalenium Custom Values
#############
## TODO: Update source URL as upstream when ArgoCD version is greater 1.5.0 or above
zalenium_values: &zalenium_values
  hub:
    serviceType: ClusterIP
    openshift:
      deploymentConfig:
        enabled: true
      route:
        enabled: true
    persistence:
      enabled: false
    serviceAccount:
      create: false
    desiredContainers: 0
    podAnnotations:
      app: zalenium

##############
# 🛎 Hoverfly Custom Values
# Values reference https://github.com/helm/charts/tree/master/incubator/hoverfly
#############
hoverfly_values: &hoverfly_values
  replicaCount: "1"
  openshift:
    route:
      admin:
        enabled: true
        hostname: ""
      proxy:
        enabled: true
        hostname: ""

##############
# 🛎 Wekan Custom Values
# Values reference https://github.com/wekan/wekan/tree/master/helm/wekan
#############
wekan_values: &wekan_values
  service:
    type: ClusterIP
  autoscaling:
    enabled: false
  mongodb-replicaset:
    replicas: 1
    securityContext:
      runAsUser: ""
      fsGroup: ""
  ingress:
    enabled: false
  route:
    enabled: true

##############
# 🛎 Mattermost Custom Values
# Values reference https://github.com/mattermost/mattermost-helm
#############
mattermost_values: &mattermost_values
  route:
    enabled: true
  mysql:
    mysqlRootPassword: "mysqlpass"
    mysqlUser: "mattermost"
    mysqlPassword: "matterpass"

##############
# 🛎 Owncloud Custom Values
#############
owncloud_values: &owncloud_values
  route:
    enabled: true
  hostname: owncloud.apps.hivec.sandbox1559.opentlc.com

#######################
# Vault Custom Values #
#######################
vault_values: &vault_values
  global:
    tlsDisable: false
  injector:
    enabled: false
  openshift: true
  server:
    route:
      host: '""'
    standalone:
      config: |
        ui = true
        listener "tcp" {
          address = "[::]:8200"
          cluster_address = "[::]:8201"
          tls_cert_file = "/var/run/secrets/kubernetes.io/certs/tls.crt"
          tls_key_file = "/var/run/secrets/kubernetes.io/certs/tls.key"
        }
        storage "file" {
          path = "/vault/data"
        }

##############
# 🐙 Argo Ignore Differences
#############
jenkins_ignore_differences: &jenkins_ignore_differences
  ignoreDifferences:
  - group: apps.openshift.io
    kind: DeploymentConfig
    jsonPointers:
    - /spec/template/spec/containers/0/image
    - /spec/triggers/0/imageChangeParams/lastTriggeredImage
  - group: build.openshift.io
    kind: BuildConfig
    jsonPointers:
    - /spec/triggers

nexus_ignore_differences: &nexus_ignore_differences
  ignoreDifferences:
  - group: route.openshift.io
    kind: Route
    jsonPointers:
    - /status/ingress

hoverflyignore_differences: &hoverfly_ignore_differences
  ignoreDifferences:
  - group: route.openshift.io
    kind: Route
    jsonPointers:
    - /status/ingress
    - /spec/host
  - group: apps/v1
    kind: Deployment
    jsonPointers:
    - /spec/replicas

crw_ignore_differences: &crw_ignore_differences
  ignoreDifferences:
  - group: org.eclipse.che
    kind: CheCluster
    jsonPointers:
    - /spec

dev-ex-dashboard_ignore_differences: &dev-ex-dashboard_ignore_differences
  ignoreDifferences:
  - group: apps.openshift.io
    kind: DeploymentConfig
    jsonPointers:
    - /spec/template/spec/containers/0/image
    - /spec/triggers/0/imageChangeParams/lastTriggeredImage
  - group: ''
    kind: ConfigMap
    jsonPointers:
    - /data

owncloud_ignore_differences: &owncloud_ignore_differences
  ignoreDifferences:
  - group: apps.openshift.io
    kind: DeploymentConfig
    jsonPointers:
    - /spec/template/spec/containers/0/image
    - /spec/triggers/0/imageChangeParams/lastTriggeredImage

vault_ignore_differences: &vault_ignore_differences
  ignoreDifferences:
  - group: route.openshift.io
    kind: Route
    jsonPointers:
    - /status/ingress
    - /spec/host

##############
# 🐙 Argo Sync Policy
#############
sync_policy_true: &sync_policy_true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      validate: true

sync_policy_no_selfheal: &sync_policy_no_selfheal
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
      validate: true

##############
# 🛎 Argo App of Apps declaration
#############

# enabled true on an app is to tell helm to create an argo app cr for this item
applications:
  - name: nexus
    enabled: true
    source: https://rht-labs.github.io/helm-charts/
    chart_name: sonatype-nexus
    source_path: ""
    source_ref: "0.0.1"
    sync_policy:
      *sync_policy_true
    destination: *ci_cd_ns
    ignore_differences: *nexus_ignore_differences
  - name: jenkins
    enabled: true
    source: https://github.com/rht-labs/helm-charts.git
    source_path: charts/jenkins
    source_ref: "feature/jenkins-sealed-secrets"
    sync_policy:
      *sync_policy_true
    destination: *ci_cd_ns
    values:
      *jenkins_values
    ignore_differences: *jenkins_ignore_differences
  - name: pact-broker
    enabled: true
    source: https://github.com/rht-labs/helm-charts.git
    source_path: charts/pact-broker
    source_ref: "pact-broker-0.0.2"
    sync_policy:
      *sync_policy_true
    destination: *ci_cd_ns
    values:
      *pact_broker_values
  - name: sonarqube
    enabled: true
    source: https://github.com/rht-labs/helm-charts.git
    source_path: charts/sonarqube
    source_ref: "sonarqube-0.0.4"
    sync_policy:
      *sync_policy_true
    destination: *ci_cd_ns
  - name: zalenium
    enabled: true
    source: https://github.com/zalando/zalenium.git
    source_path: charts/zalenium
    source_ref: "master"
    sync_policy:
      *sync_policy_true
    destination: *ci_cd_ns
    values:
      *zalenium_values
  - name: hoverfly
    enabled: true
    source: https://github.com/helm/charts.git
    source_path: incubator/hoverfly
    sync_policy:
      *sync_policy_true
    destination: *ci_cd_ns
    source_ref: "master"
    values:
      *hoverfly_values
    ignore_differences: *hoverfly_ignore_differences
  - name: wekan
    enabled: true
    source: https://github.com/wekan/wekan.git
    source_path: helm/wekan
    sync_policy:
      *sync_policy_true
    destination: *ci_cd_ns
    source_ref: "v4.01"
    values:
      *wekan_values
